using System;
using Interfaz;
using menuSeleccionable;
using Musica;
using MonstersApi;
using Rutas;
using FabricaDePersonajes;
Console.CursorVisible = false;
await consumiendoApi.Get();
Music.Inicio();
Cartel.TituloJuego(7);
CrearPersonaje.GenerarPersonajes(6);
menuu.menu();
