using System;
using Interfaz;
using menuSeleccionable;
using Musica;
using MonstersApi;
using Rutas;
using FabricaDePersonajes;
await consumiendoApi.Get();
Music.Inicio();
Cartel.TituloJuego(7);
CrearPersonaje.GenerarPersonajes(5);
menuu.menu();
